POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite Summit 2",
    "details": "Um evento para quem é apaixonado por programação.",
    "maximumAttendees": 100
}

###

POST http://localhost:3333/events/f4ca657c-e7f1-413d-a5d0-de199b937eea/attendee
Content-Type: application/json

{
    "name": "Matheus Marinho",
    "email": "matheus.marinhodsp@gmail.com"
}

###

GET http://localhost:3333/events/f4ca657c-e7f1-413d-a5d0-de199b937eea

### 

GET http://localhost:3333/attendees/1/badge